/**
 * PowerWatch - Cloud Report Generator Controller
 * Configurable audit templates, interactive printable letterhead preview,
 * CSV export, and PDF print formatting.
 */

class ReportsController {
  constructor() {
    this.reportType = 'monthly';
    this.targetBuilding = 'all';
    this.startDate = new Date(Date.now() - 30 * 86400000).toISOString().slice(0,10);
    this.endDate = new Date().toISOString().slice(0,10);

    this.init();
  }

  init() {
    this.initEventListeners();
    this.populateBuildingOptions();
    this.generateReport();
  }

  initEventListeners() {
    const typeSelect = document.getElementById('reportTypeSelect');
    if (typeSelect) {
      typeSelect.addEventListener('change', (e) => {
        this.reportType = e.target.value;
        this.generateReport();
      });
    }

    const bldSelect = document.getElementById('reportBuildingSelect');
    if (bldSelect) {
      bldSelect.addEventListener('change', (e) => {
        this.targetBuilding = e.target.value;
        this.generateReport();
      });
    }

    const btnGenerate = document.getElementById('btnGenerateReport');
    if (btnGenerate) {
      btnGenerate.addEventListener('click', () => this.generateReport());
    }

    const btnPrint = document.getElementById('btnPrintReport');
    if (btnPrint) {
      btnPrint.addEventListener('click', () => window.print());
    }

    const btnCSV = document.getElementById('btnDownloadReportCSV');
    if (btnCSV) {
      btnCSV.addEventListener('click', () => this.exportReportCSV());
    }
  }

  populateBuildingOptions() {
    const select = document.getElementById('reportBuildingSelect');
    if (!select) return;

    const blds = window.cloudStore ? window.cloudStore.collections.buildings : SEED_BUILDINGS;
    let opts = '<option value="all">All Campus Buildings</option>';
    blds.forEach(b => {
      opts += `<option value="${b.id}">${b.name} (${b.code})</option>`;
    });
    select.innerHTML = opts;
  }

  generateReport() {
    const previewContainer = document.getElementById('reportPreviewContainer');
    if (!previewContainer) return;

    const settings = window.cloudStore ? window.cloudStore.getSettings() : DEFAULT_SETTINGS;
    const baseTariff = settings.tariff.baseRate || 7.5;
    const peakSurchargePct = settings.tariff.peakSurchargePercent || 20;

    let targetBlds = window.cloudStore ? window.cloudStore.collections.buildings : SEED_BUILDINGS;
    if (this.targetBuilding !== 'all') {
      targetBlds = targetBlds.filter(b => b.id === this.targetBuilding);
    }

    const totalConsumption = targetBlds.reduce((sum, b) => sum + (this.reportType === 'daily' ? b.dailyConsumption : b.monthlyConsumption), 0);
    const baseCost = totalConsumption * baseTariff;
    const surchargeCost = baseCost * (peakSurchargePct / 100) * 0.35; // ~35% peak load fraction
    const totalCost = baseCost + surchargeCost;
    const avgEfficiency = Math.round(targetBlds.reduce((sum, b) => sum + b.efficiencyScore, 0) / targetBlds.length);
    const carbonKg = Math.round(totalConsumption * 0.82);

    const reportId = `PW-AUDIT-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;
    const user = window.authManager ? window.authManager.getCurrentUser() : { name: "System Administrator", role: "Admin" };

    previewContainer.innerHTML = `
      <div class="card" style="background: var(--bg-card); padding: 2.5rem; border: 1px solid var(--border-color); box-shadow: var(--shadow-lg);">
        <!-- PowerWatch Official Header -->
        <div class="report-print-header" style="display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid var(--border-color); padding-bottom: 1.5rem; margin-bottom: 2rem;">
          <div>
            <div style="display: flex; align-items: center; gap: 0.65rem; margin-bottom: 0.35rem;">
              <div class="brand-logo" style="width: 34px; height: 34px;">
                <i data-lucide="zap" style="width: 18px; height: 18px;"></i>
              </div>
              <h2 style="font-family: var(--font-display); font-size: 1.6rem; color: var(--text-primary);">Power<span>Watch</span></h2>
            </div>
            <div style="font-size: 0.82rem; color: var(--text-muted);">Cloud-Based Smart Energy Monitoring & Analytics Platform</div>
            <div style="font-size: 0.78rem; color: var(--text-dim); margin-top: 0.2rem;">Organization: ${settings.organization.name}</div>
          </div>

          <div style="text-align: right; font-size: 0.82rem;">
            <div style="font-weight: 700; color: var(--accent-cyan); font-family: var(--font-mono); font-size: 0.95rem;">${reportId}</div>
            <div style="color: var(--text-muted); margin-top: 0.25rem;">Date: <strong>${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</strong></div>
            <div style="color: var(--text-muted);">Generated By: <strong>${user.name}</strong> (${user.role})</div>
            <span class="badge badge-cyan" style="margin-top: 0.4rem;">${this.reportType.toUpperCase()} ENERGY AUDIT</span>
          </div>
        </div>

        <!-- KPI Grid -->
        <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-bottom: 2rem;">
          <div style="background: var(--bg-tertiary); padding: 1rem; border-radius: var(--radius-md); border: 1px solid var(--border-color);">
            <div style="font-size: 0.72rem; color: var(--text-muted); text-transform: uppercase;">Total Energy</div>
            <div class="font-mono" style="font-size: 1.35rem; font-weight: 700; color: var(--text-primary); margin-top: 0.2rem;">${totalConsumption.toLocaleString('en-IN')} kWh</div>
          </div>
          <div style="background: var(--bg-tertiary); padding: 1rem; border-radius: var(--radius-md); border: 1px solid var(--border-color);">
            <div style="font-size: 0.72rem; color: var(--text-muted); text-transform: uppercase;">Estimated Total Cost</div>
            <div class="font-mono" style="font-size: 1.35rem; font-weight: 700; color: var(--color-success); margin-top: 0.2rem;">₹${Math.round(totalCost).toLocaleString('en-IN')}</div>
          </div>
          <div style="background: var(--bg-tertiary); padding: 1rem; border-radius: var(--radius-md); border: 1px solid var(--border-color);">
            <div style="font-size: 0.72rem; color: var(--text-muted); text-transform: uppercase;">Campus Efficiency</div>
            <div class="font-mono" style="font-size: 1.35rem; font-weight: 700; color: var(--accent-cyan); margin-top: 0.2rem;">${avgEfficiency}%</div>
          </div>
          <div style="background: var(--bg-tertiary); padding: 1rem; border-radius: var(--radius-md); border: 1px solid var(--border-color);">
            <div style="font-size: 0.72rem; color: var(--text-muted); text-transform: uppercase;">Carbon Emissions</div>
            <div class="font-mono" style="font-size: 1.35rem; font-weight: 700; color: var(--color-warning); margin-top: 0.2rem;">${(carbonKg / 1000).toFixed(1)} MT CO₂</div>
          </div>
        </div>

        <!-- Tabular Breakdown -->
        <h3 style="font-size: 1.1rem; margin-bottom: 0.75rem; color: var(--text-primary);">Building-by-Building Consumption & Cost Breakdown</h3>
        <div class="table-container" style="margin-bottom: 2rem;">
          <table class="table-custom">
            <thead>
              <tr>
                <th>Building</th>
                <th>Category</th>
                <th>Energy (kWh)</th>
                <th>Base Cost (@ ₹${baseTariff}/kWh)</th>
                <th>Peak Surcharge</th>
                <th>Total Cost (₹)</th>
                <th>Efficiency</th>
              </tr>
            </thead>
            <tbody>
              ${targetBlds.map(b => {
                const kwh = this.reportType === 'daily' ? b.dailyConsumption : b.monthlyConsumption;
                const bBase = kwh * baseTariff;
                const bSur = bBase * (peakSurchargePct / 100) * 0.35;
                const bTot = bBase + bSur;
                return `
                  <tr>
                    <td><strong>${b.name}</strong> <span style="font-size: 0.72rem; color: var(--text-muted); font-family: var(--font-mono);">(${b.code})</span></td>
                    <td><span class="badge badge-neutral">${b.category}</span></td>
                    <td class="font-mono" style="font-weight: 700; color: var(--accent-cyan);">${kwh.toLocaleString('en-IN')}</td>
                    <td class="font-mono">₹${Math.round(bBase).toLocaleString('en-IN')}</td>
                    <td class="font-mono" style="color: var(--color-warning);">+₹${Math.round(bSur).toLocaleString('en-IN')}</td>
                    <td class="font-mono" style="font-weight: 700; color: var(--color-success);">₹${Math.round(bTot).toLocaleString('en-IN')}</td>
                    <td class="font-mono">${b.efficiencyScore}%</td>
                  </tr>
                `;
              }).join('')}
            </tbody>
          </table>
        </div>

        <!-- Tariff Formula & Calculation Note -->
        <div style="background: var(--bg-tertiary); padding: 1.25rem; border-radius: var(--radius-md); border: 1px solid var(--border-color); margin-bottom: 2rem; font-size: 0.85rem;">
          <div style="font-weight: 700; color: var(--accent-cyan); margin-bottom: 0.35rem; display: flex; align-items: center; gap: 0.35rem;">
            <i data-lucide="calculator" style="width: 16px; height: 16px;"></i> Tariff Calculation Methodology
          </div>
          <div style="color: var(--text-secondary); line-height: 1.5;">
            Total Estimated Cost = (Energy Consumption × Base Tariff Rate) + (Peak-Hour Consumption × Surcharge %) + Fixed Demand Charges.<br/>
            Current Configured Rates: <strong>₹${baseTariff.toFixed(2)} per kWh</strong> base rate, <strong>+${peakSurchargePct}%</strong> peak window surcharge (10:00 - 14:00, 18:00 - 22:00).
          </div>
        </div>

        <!-- Recommendations Section -->
        <h3 style="font-size: 1.1rem; margin-bottom: 0.75rem; color: var(--text-primary);">Audit Findings & Energy Optimization Recommendations</h3>
        <div style="display: flex; flex-direction: column; gap: 0.75rem; font-size: 0.85rem;">
          <div style="padding: 0.85rem 1rem; background: rgba(0, 240, 255, 0.05); border: 1px solid rgba(0, 240, 255, 0.2); border-radius: var(--radius-md);">
            <strong style="color: var(--accent-cyan);">1. Computer Center Peak Shaving:</strong> Server Room cooling operates at continuous peak. Staggering batch simulation jobs to off-peak slots (23:00 - 05:00) can save an estimated <strong>₹14,500/mo</strong>.
          </div>
          <div style="padding: 0.85rem 1rem; background: rgba(16, 185, 129, 0.05); border: 1px solid rgba(16, 185, 129, 0.2); border-radius: var(--radius-md);">
            <strong style="color: var(--color-success);">2. Power Factor Compliance:</strong> APFC capacitor banks across Mechanical Block maintained a 0.94 average PF, preventing DISCOM low PF surcharges this cycle.
          </div>
        </div>
      </div>
    `;

    if (window.lucide) window.lucide.createIcons();
  }

  exportReportCSV() {
    let targetBlds = window.cloudStore ? window.cloudStore.collections.buildings : SEED_BUILDINGS;
    if (this.targetBuilding !== 'all') {
      targetBlds = targetBlds.filter(b => b.id === this.targetBuilding);
    }
    const settings = window.cloudStore ? window.cloudStore.getSettings() : DEFAULT_SETTINGS;
    const baseTariff = settings.tariff.baseRate || 7.5;

    let csv = "Building,Code,Category,Energy (kWh),Base Tariff (INR/kWh),Estimated Cost (INR),Efficiency Score (%)\n";
    targetBlds.forEach(b => {
      const kwh = this.reportType === 'daily' ? b.dailyConsumption : b.monthlyConsumption;
      const cost = Math.round(kwh * baseTariff);
      csv += `"${b.name}","${b.code}","${b.category}",${kwh},${baseTariff},${cost},${b.efficiencyScore}\n`;
    });

    PowerWatchUtils.downloadCSV(`PowerWatch_Report_${this.reportType}_${new Date().toISOString().slice(0,10)}.csv`, csv);
    PowerWatchUtils.showToast("Report Exported", "Report CSV downloaded successfully.", "success");
  }
}

document.addEventListener('DOMContentLoaded', () => {
  window.reportsController = new ReportsController();
});
